### ISSUE TITLE
Error updating a widget

### ISSUE THREAD

**Issue by lmreyes** [fiwoo-platform/Data-Visualization#10]
The method PUT from widget doesn't work correctly. The method delete the widget and create other one.
The method should only change the values.

**Comment by rcarballoc** [comment]
https://github.com/fiwoo-platform/Data-Visualization/commit/7150ff9483d11ff2fafc32e9c31f75ad3cb22235

**Comment by dlozanoarenal** [comment]
@rcarballoc esto ya está terminado, no?

**Comment by rcarballoc** [comment]
is solved?
