### ISSUE TITLE
Need more widget types

### ISSUE THREAD

**Issue by jordiJIG** [fiwoo-platform/Data-Visualization#54]
Need to add some widget types to the enum.

For example: batteryWidget, booleanWidget and digitalWidget

**Comment by rcarballoc** [comment]
Could you please be more exhaustive? Thanks

**Comment by jordiJIG** [comment]
![image](https://user-images.githubusercontent.com/19531028/38679037-f709d152-3e62-11e8-8506-2038ecb8dc08.png)

**Comment by rcarballoc** [comment]
Changes pending for integration in master
