### ISSUE TITLE
Error updating a dashboard

### ISSUE THREAD

**Issue by lmreyes** [fiwoo-platform/Data-Visualization#9]
The method PUT from dashboard doesn't work correctly. The method delete the dashboard and create other one. 
**The method should only change the data.**

**Comment by rcarballoc** [comment]
https://github.com/fiwoo-platform/Data-Visualization/commit/7150ff9483d11ff2fafc32e9c31f75ad3cb22235

**Comment by dlozanoarenal** [comment]
@rcarballoc esto está finalizado, no?

**Comment by rcarballoc** [comment]
is solved?
